version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ostore_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - ostore_network

  # O!Store Agent API (Ollama-compatible)
  ostore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ostore_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - ostore_network
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  # OpenWebUI (Optional - for testing)
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ostore_openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:8000
      - WEBUI_SECRET_KEY=your_secret_key_here
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ostore_network
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped

volumes:
  qdrant_data:
  openwebui_data:

networks:
  ostore_network:
    driver: bridge